name: Publish Docker image
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        MONGO_CONNECTIONSTRING: ${{ secrets.MONGO_CONNECTIONSTRING }}
      with:
        name: oliverkramer/skoleprotokol
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    	buildargs: MONGO_CONNECTIONSTRING