name: Publish Docker image
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: master
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
	env:
	  MONGO_CONNECTIONSTRING: ${{ secrets.MONGO_CONNECTIONSTRING }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: oliverkramer/skoleprotokol
          tag_with_ref: true


